# Generated by Django 5.2.7 on 2026-08-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_following_post_user_liked_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disliked_posts',
            field=models.ManyToManyField(blank=True, related_name='disliked_by', to='network.post'),
        ),
    ]
